### ISSUE TITLE
使用mp.spawn启动比torch.distributed.launch慢很多

### ISSUE THREAD

**Issue by WZMIAOMIAO** [tczhangzhi/pytorch-distributed#7]
作者您好，我最近测试多GPU训练时遇到了使用mp.spawn启动比torch.distributed.launch慢很多的情况。
我发现使用mp.spawn方法后，每次个epoch开始时都会等待很久，但使用torch.distributed.launch启动时就没有出现这种情况。请问作者您在使用过程中有出现这种情况吗？

**Comment by tczhangzhi** [comment]
First, m afraid `distributed.launch` is the best practice if u don't need to custom the multiprocessing process.
In detail, `mp.spawn` is slow because its initialization or re-initialization is time-consuming, especially when you start multiple workers to load the dataset. This process is necessary to help you move data to the shared memory and perform the `Tensor` transfers between processes. Of course, you can handle it manually with `Process()`, `share_memory()`, and other APIs. For more detail, please refer to [the document](https://pytorch.org/docs/stable/notes/multiprocessing.html).

**Comment by WZMIAOMIAO** [comment]
Thank you for your reply.
